CREATE TABLE CADASTRO (
    [IDPESSOA]      INT          IDENTITY (1, 1) NOT NULL,
    [NOMEPESSOA]    VARCHAR (50) NULL,
    [ADDRESSPESSOA] VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([IDPESSOA] ASC)
);

